---
title: "Visualisation"
author: "Pooja Shah"
date: "12/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggrepel)
```

```{r}
austin_airport = read.csv("ABIA.csv")
airport_codes = read.csv("airport-codes.csv")
```

```{r}
us_airport_codes = subset(airport_codes, airport_codes$iso_country == 'US', select = c(iata_code, coordinates))
us_airport_codes = separate(us_airport_codes, coordinates, c("longitude", "latitude"), sep = ", ")
us_airport_codes$longitude = as.numeric(us_airport_codes$longitude)
us_airport_codes$latitude = as.numeric(us_airport_codes$latitude)
us_airport_codes$iata_code = as.character(us_airport_codes$iata_code)
us_airport_codes = us_airport_codes[!(is.na(us_airport_codes$iata_code) | us_airport_codes$iata_code == ""), ]
austin_airport = austin_airport[!(is.na(austin_airport$Origin) | austin_airport$Origin == ""), ]
austin_airport = austin_airport[!(is.na(austin_airport$Dest) | austin_airport$Dest == ""), ]
austin_airport$Origin = as.character(austin_airport$Origin)
austin_airport$Dest = as.character(austin_airport$Dest)
austin_airport$Month = as.factor(austin_airport$Month)
austin_airport$Cancelled = as.factor(austin_airport$Cancelled)
austin_airport$DayOfWeek = as.factor(austin_airport$DayOfWeek)
```

```{r}
austin_airport <- merge(austin_airport, us_airport_codes, by.x="Dest", by.y="iata_code")
austin_airport <- merge(austin_airport, us_airport_codes, by.x="Origin", by.y="iata_code")
```

```{r}
austin_airport['route'] = paste(austin_airport$Origin, " ", austin_airport$Dest)
austin_unique = distinct(austin_airport, route, .keep_all = TRUE)
```

```{r}
route_counts = distinct(austin_airport %>% group_by(route, latitude.x, latitude.y, longitude.x, longitude.y) %>% summarise(count = n())) 
top_10 = head(arrange(route_counts, desc(count)), 10)
```

```{r}
austin_unique = transform(austin_unique, Origin = ifelse(Dest != 'AUS', Origin, Dest), Dest = ifelse(Dest != 'AUS', Dest,Origin))

austin_unique = distinct(austin_unique,Origin,Dest,.keep_all = T)
```

```{r}
usmap <- borders("usa") 
ggplot() + usmap + 
 geom_curve(data = austin_unique, aes(x = latitude.x, y = longitude.x, xend = latitude.y, yend = longitude.y)) + 
 #geom_point(data = us_airport_codes, aes(x = longitude, y = latitude), ) + 
 theme(panel.background = element_rect(fill = "white"), 
 axis.line = element_blank(),
 axis.text.x = element_blank(),
 axis.text.y = element_blank(),
 axis.ticks = element_blank(),
 axis.title.x = element_blank(),
 axis.title.y = element_blank()
 )
```

Trying to plot the number of cancelled flights by Day of the Week(could also be done by Month) and Flight Carrier. Data is imbalanced so i dont know if it can be used or not. I have done it by time of day after this.
```{r}
cancelled_flights = austin_airport[austin_airport$Cancelled == 1,]
table(cancelled_flights$UniqueCarrier)
group = austin_airport %>%
  group_by(DayOfWeek, UniqueCarrier)  %>% 
  summarize(count = sum(Cancelled == 1))
ggplot(data = group, aes(x = DayOfWeek, y = count)) +
        geom_bar(stat = 'identity') + 
        facet_wrap(~UniqueCarrier)
```
```{r}
austin_airport['dep_time'] = as.integer(austin_airport$CRSDepTime / 100)
austin_airport['dep_time_period'] = ifelse(austin_airport$dep_time >=0 & austin_airport$dep_time < 12, 'Morning', ifelse(austin_airport$dep_time >= 12 & austin_airport$dep_time < 16, 'Afternoon', ifelse(austin_airport$dep_time >=14 && austin_airport$dep_time < 20, 'Evening', 'Night')))                  
table(austin_airport$dep_time_period)
austin_airport$dep_time = as.factor(austin_airport$dep_time)
austin_airport$dep_time_period = as.factor(austin_airport$dep_time_period)
group = austin_airport %>%
  group_by(dep_time_period, UniqueCarrier)  %>% 
  summarize(count = sum(Cancelled == 1))
ggplot(data = group, aes(x = dep_time_period, y = count)) +
        geom_bar(stat = 'identity') + 
        facet_wrap(~UniqueCarrier)
```

```{r}

flip_origin_dest = transform(austin_airport, Origin = ifelse(Dest != 'AUS', Origin, Dest), Dest = ifelse(Dest != 'AUS', Dest,Origin)) # simply changes all the origins to be austin; doesn't change the rest of the dataset

austin_unique = distinct(flip_origin_dest,Origin,Dest,.keep_all = T) # drops duplicates



usmap <- borders("usa") 

ggplot() + usmap + 

 geom_curve(data = austin_unique, aes(x = latitude.x, y = longitude.x, xend = latitude.y, yend = longitude.y, colour = DepDelay)) +

 #scale_color_brewer(palette = "YlOrRd")+

 #geom_point(data = us_airport_codes, aes(x = longitude, y = latitude), ) + 

 theme(panel.background = element_rect(fill = "white"), 

 axis.line = element_blank(),

 axis.text.x = element_blank(),

 axis.text.y = element_blank(),

 axis.ticks = element_blank(),

 axis.title.x = element_blank(),

 axis.title.y = element_blank()

 )

```



```{r}

most_common = flip_origin_dest %>% count(Dest) # all of the common places to fly to/from

most_common = most_common[order(-most_common$n),]



austin_counts = merge(austin_unique, most_common, by = c("Dest","Dest"))

colnames(austin_counts)[colnames(austin_counts)=="n"] = "counts"

austin_counts

```



```{r}

usmap <- borders("usa") 

ggplot() + usmap + 

 geom_curve(data = austin_counts, aes(x = latitude.x, y = longitude.x, xend = latitude.y, yend = longitude.y, colour = counts)) +

 #scale_color_brewer(palette = "YlOrRd")+

 #geom_point(data = us_airport_codes, aes(x = longitude, y = latitude), ) + 

 theme(panel.background = element_rect(fill = "white"), 

 axis.line = element_blank(),

 axis.text.x = element_blank(),

 axis.text.y = element_blank(),

 axis.ticks = element_blank(),

 axis.title.x = element_blank(),

 axis.title.y = element_blank()

 )

```

