---
title: "Visualizations"
author: "Pooja Shah"
date: "10/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mosaic)
library(tidyverse)
buildings = read.csv('greenbuildings.csv')
```

```{r}
buildings$green_rating = as.factor(buildings$green_rating)
buildings$LEED = as.factor(buildings$LEED)
buildings$Energystar = as.factor(buildings$Energystar)
buildings$amenities = as.factor(buildings$amenities)
buildings$renovated = as.factor(buildings$renovated)
buildings$class_a = as.factor(buildings$class_a)
buildings$class_b = as.factor(buildings$class_b)
buildings$net = as.factor(buildings$net)
```

```{r}
ggplot(data = buildings) + 
  geom_boxplot(mapping = aes(x = green_rating, y = Rent, colour = green_rating)) + labs(title = 'Comparison between Rents in Normal V/S Sustainable Buildings')
```
The above graph shows that the rents in both kinds of buildings tend to be around the same. There are more buildings that are not sustainable with above average rent.

```{r}
buildings$class = ifelse(buildings$class_a == 1, 'A', ifelse(buildings$class_b == 1, 'B', 'C'))
```

```{r}
ggplot(data = buildings) + 
  geom_boxplot(mapping = aes(x = green_rating, y = leasing_rate, colour = green_rating)) + labs(title = 'Comparison between Leasting Rates in Normal V/S Sustainable Buildings')
```
```{r}
green_building = buildings[buildings$green_rating == 1,]
hist(green_building$leasing_rate)
```
